apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: hlf
spec:
  version: "v1.6.0"
  homepage: https://github.com/kfsoftware/hlf-operator
  shortDescription: "Deploy and manage Hyperledger Fabric Peers, Orderers and Certificate authorities"
  description: |
    The hlf plugin wraps the Hyperledger Fabric Operator and provides a simple
    interface to create and manage Hyperledger Fabric Peers, Orderers, and Certificate authorities.
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/hyperledger/bevel-operator-fabric/releases/download/v1.6.3/hlf-operator_v1.6.3_linux_amd64.zip
      sha256: 74590bcb4cea80a5a3a5d69d97683d222117bd8eaff268380acfbd318f542acc
      bin: kubectl-hlf